start draft of incubation status/incubating packages
planetarypy/TC pull request #98
Opened 2024-03-30 18:19 UTC by AndrewAnnex

Progress towards defining what a incubating project is and (minimal) review criteria. Will require new page/list on the planetarypy website. Looking for feedback otherwise!

2024-04-06 16:04 UTC, rbeyer commented
How do you want contributions?  Put text in comments for you to commit or direct commit to PR branch?

2024-04-06 16:13 UTC, AndrewAnnex commented
Whichever works for you!- Dr. Andrew AnnexOn Apr 6, 2024, at 9:05 AM, Ross Beyer ***@***.***> wrote:﻿
How do you want contributions?  Put text in comments for you to commit or direct commit to PR branch?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-04-16 20:40 UTC, cjtu commented
I don't have write access to TC so seems like I can't push changes to the PR - even from a fork. But here are my edits - general proofing and making the Incubation Package/Status verbage consistent.


```markdown
# PlanetaryPy Incubation Packages

Packages in PlanetaryPy Incubation are packages that might eventually join PlanetaryPy as an Affiliated Package. Entering incubation is not a requirement or prerequisite for being an Affiliated Package. Incubation status is intended to foster the development of packages that may not yet fully meet all of the standards of an Affiliated Package.

There are no time-limits to project incubation status or requirement that packages ever submit for review as an Affiliated Package to PlanetaryPy. However, if a Planetarypy Incubation Package does successfully become a PlanetaryPy Affiliated Package, it will no longer be considered under incubation.

Once accepted as an Incubation Package, the developers are expected to attend at least one PlaneatryPy Technical Committee (TC) meeting to discuss their Incubation Package. The intent is so that the TC can better understand the package, and provide advice and help to the developers on a wide spectrum of topics like open source best practices, standards, or any other topic that the developers would like help or guidance navigating. Of course, Incubation Package developers are welcome (like anyone else) to join PlanetaryPy TC meetings, even before they might submit a package to be considered.

Incubation Packages receive a number of benefits. Just being in this public listing might help users find their functionality more easily, and provides the opportunity for more users and even contributors to get involved with the Incubation Package. Additionally, the TC will be able to direct people to these packages when individuals ask "how they can help" PlanetaryPy. In partnership with the developers, the TC may make the package a part of hack-a-thons or other directed community contribution events or campaigns. Being an Incubation Package is an opportunity, and the TC wants to help those packages succeed.

## How submit a Package for Incubation

If you are a developer of a planetary science package and would like your package to be in PlanetaryPy Incubation status, simply open a pull request following the process laid out [in proposing a project for incubation]. All that is required is the name of the project, link to the GitHub repository, the software license (if applicable), the code of conduct for the project or deferral to PlanetaryPy's code of conduct (see below), and 1-2 sentences explaining what the package does. No other review criteria need to be met.

Once the submission is successfully merged the project will be listed as being in Incubation on the PlanetaryPy website. 

Packages will retain the Incubation status so long as the project developers wish, and they may withdraw their package from PlanetaryPy incubation at any time. The PlanetaryPy TC will only remove packages from Incubation status if:

1. The package becomes an Affiliated Package of PlanetaryPy.
2. If the package developers violate the PlanetaryPy Code of Conduct or adopt a Code of Conduct sufficiently divergent from the PlanetaryPy Code of Conduct (see below).
3. Inactivity or inability to establish communication with the Incubation Package developers lasting more than two calendar years from the date of acceptance or last contact.

### Community Standards and Governance

The PlanetaryPy Project believes that good software is an outcome
of a healthy open-source community. The PlanetaryPy project operates
under rules laid out in its [Charter](Charter.md) as well as the
[Code of Conduct](Code-Of-Conduct.md), [Contributing
Guidelines](Contributing.md), and other documents that we'll refer
to as 'governing documents.' If an Incubation Package does not
explicitly define their own governing documents, it is assumed that
those of the PlanetaryPy Project apply. Incubation Packages are
absolutely welcome to explicitly define their own versions of these
documents that govern how they operate, but if these documents or
the behavior of the Incubation Package's community diverges
significantly from those of the PlanetaryPy Project, or if they diverge after
being accepted as an Incubation Package, this may be the basis for
being removed from the list of Incubation packages.

[incubation-process]: https://planetarypy.org/packages/incubation-process/
```

2024-04-16 20:42 UTC, cjtu commented
Q: is there a reason community standards section has line breaks and the rest is 1 para/line markdown style? Might render weird on some screens

2024-09-16 16:16 UTC, michaelaye commented on Incubation.md
> +Once accepted as an Incubation Package, the developers are expected to attend at least one PlaneatryPy Technical Committee (TC) meeting to discuss their Incubation Package. The intent is so that the
spelling of PlanetaryPy

2024-09-16 16:18 UTC, michaelaye requested changes
just one typo to correct, otherwise good to merge.

2024-09-17 19:40 UTC, AndrewAnnex reviewed
fix typo

2025-06-17 19:00 UTC, merged